title: "Notas de aula: Sistemas Distribuídos"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: false
github_username: lasarojc

#Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - unused

search_tokenizer_separator: /[\s/]+/
