title: "Sistemas Distribuídos"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
github_username: lasarojc

#Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - unused

search_tokenizer_separator: /[\s/]+/

mathjax: true
