site_name: Sistemas Distribuídos
nav:
        - Prólogo: index.md
        - Introdução: intro/index.md
        - Fundamentos: basics/index.md
theme: readthedocs
markdown_extensions:
        - mdx_math
        - admonition
        - footnotes
extra_javascript:
        - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
        - mathjaxhelper.js

