site_name: Sistemas Distribuídos
nav:
        - Prólogo: index.md
        - Introdução: intro/index.md
        - Fundamentos: basics/index.md
theme: readthedocs
markdown_extensions:
        - admonition
        - footnotes

